#!/usr/bin/env bash

LNG=$(../bin/xkblayout-state print %s | awk '{print toupper($0)}')
case $LNG in
  "US")
    CLR=\#00FF00 ;; # green
  "RU")
    CLR=\#FF0000 ;; # red
  *)
    CLR=\#FFFFFF ;; # all others default-white
esac
echo "$LNG"
echo "$CLR"
